{
 "title": "Data for device",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "device_id", "label": "Device id" },
   {
    "name": "device",
    "query": "SELECT description FROM devices WHERE id= $device_id"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "UTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT description FROM devices WHERE id = $device_id",
     "rawQueryText": "SELECT description FROM devices WHERE id = $device_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "UTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT strftime('%d/%m/%Y %H:%M', MAX(sensor_data.ts), 'unixepoch') AS updated_at\nFROM sensor_data WHERE device = $device_id",
     "rawQueryText": "SELECT strftime('%d/%m/%Y %H:%M', MAX(sensor_data.ts), 'unixepoch') AS updated_at\nFROM sensor_data WHERE device = $device_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Stations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "queryText": "SELECT\n  devices.id,\n  devices.description, \n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'temperature' THEN sensor_data.value ELSE NULL END) AS temp,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'pressure' THEN sensor_data.value ELSE NULL END) AS pressure,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'dew' THEN sensor_data.value ELSE NULL END) AS dew,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'gps' THEN sensor_data.value ELSE NULL END) AS gps,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'baro' THEN sensor_data.value ELSE NULL END) AS baro,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'humidity' THEN sensor_data.value ELSE NULL END) AS humidity\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'heat' THEN sensor_data.value ELSE NULL END) AS heat\nFROM devices \nJOIN sensor_data ON devices.id = sensor_data.device \nWHERE sensor_data.ts = (SELECT MAX(ts) FROM sensor_data s WHERE s.device = sensor_data.device AND s.type = sensor_data.type)\nGROUP BY devices.device;",
       "rawQueryText": "SELECT\n  devices.id,\n  devices.description, \n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'temperature' THEN sensor_data.value ELSE NULL END) AS temp,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'pressure' THEN sensor_data.value ELSE NULL END) AS pressure,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'dew' THEN sensor_data.value ELSE NULL END) AS dew,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'gps' THEN sensor_data.value ELSE NULL END) AS gps,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'baro' THEN sensor_data.value ELSE NULL END) AS baro,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'humidity' THEN sensor_data.value ELSE NULL END) AS humidity\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'heat' THEN sensor_data.value ELSE NULL END) AS heat\nFROM devices \nJOIN sensor_data ON devices.id = sensor_data.device \nWHERE sensor_data.ts = (SELECT MAX(ts) FROM sensor_data s WHERE s.device = sensor_data.device AND s.type = sensor_data.type)\nGROUP BY devices.device;"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Amplitudes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amplitude °C",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "rawQueryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Amplitude Pressure",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "rawQueryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Amplitude Humidity",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "rawQueryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Amplitude Altitude",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "rawQueryText": "SELECT ABS(MAX(value) - MIN(value)) AS diff FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}",
     "rawQueryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "queryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "queryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "GPS Altitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "queryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, value FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "GEO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "geomap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "targets": [
      {
       "queryText": "SELECT lat, lot\nFROM sensor_data WHERE device = $device_id\nORDER BY ts DESC LIMIT 1",
       "rawQueryText": "SELECT lat, lot\nFROM sensor_data WHERE device = $device_id\nORDER BY ts DESC LIMIT 1",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}