{
 "title": "Data for device",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device_id", "label": "Device id" },
   {
    "name": "device",
    "query": "SELECT description FROM devices WHERE id= $device_id"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "UTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT description FROM devices WHERE id = $device_id",
     "rawQueryText": "SELECT description FROM devices WHERE id = $device_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last Datetime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT MAX(sensor_data.ts)*1000 AS updated_at\nFROM sensor_data WHERE device = $device_id",
     "rawQueryText": "SELECT MAX(sensor_data.ts)*1000 AS updated_at\nFROM sensor_data WHERE device = $device_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Stations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT\n  devices.id,\n  devices.description, \n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'temperature' THEN sensor_data.value ELSE NULL END) AS temp,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'pressure' THEN sensor_data.value ELSE NULL END) AS pressure,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'dew' THEN sensor_data.value ELSE NULL END) AS dew,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'gps' THEN sensor_data.value ELSE NULL END) AS gps,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'baro' THEN sensor_data.value ELSE NULL END) AS baro,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'humidity' THEN sensor_data.value ELSE NULL END) AS humidity\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'heat' THEN sensor_data.value ELSE NULL END) AS heat\nFROM devices \nJOIN sensor_data ON devices.id = sensor_data.device \nWHERE sensor_data.ts = (SELECT MAX(ts) FROM sensor_data s WHERE s.device = sensor_data.device AND s.type = sensor_data.type)\nGROUP BY devices.device;",
     "rawQueryText": "SELECT\n  devices.id,\n  devices.description, \n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'temperature' THEN sensor_data.value ELSE NULL END) AS temp,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'pressure' THEN sensor_data.value ELSE NULL END) AS pressure,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'dew' THEN sensor_data.value ELSE NULL END) AS dew,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'gps' THEN sensor_data.value ELSE NULL END) AS gps,\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'baro' THEN sensor_data.value ELSE NULL END) AS baro,\n  GROUP_CONCAT(CASE WHEN sensor_data.type = 'humidity' THEN sensor_data.value ELSE NULL END) AS humidity\n  -- GROUP_CONCAT(CASE WHEN sensor_data.type = 'heat' THEN sensor_data.value ELSE NULL END) AS heat\nFROM devices \nJOIN sensor_data ON devices.id = sensor_data.device \nWHERE sensor_data.ts = (SELECT MAX(ts) FROM sensor_data s WHERE s.device = sensor_data.device AND s.type = sensor_data.type)\nGROUP BY devices.device;"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' ORDER BY ts DESC\nLIMIT 1",
     "rawQueryText": "SELECT `value`\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' ORDER BY ts DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Amplitudes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Amplitude °C",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'temperature'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'temperature'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "rawQueryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'temperature'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'temperature'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Amplitude Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'pressure'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'pressure'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "rawQueryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'pressure'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'pressure'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Amplitude Humidity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'humidity'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'humidity'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "rawQueryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'humidity'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'humidity'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Amplitude Altitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'gps'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'gps'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "rawQueryText": "SELECT \n    CASE \n        WHEN \n        (\n            -- timestamp of bigest value\n            SELECT MAX(ts) FROM\n            (\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'gps'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` DESC\n                LIMIT 1\n            )\n        ) > \n        (\n        SELECT MIN(ts) FROM\n            (\n                -- timestamp of lowest value\n                SELECT `value`, ts\n                FROM sensor_data \n                WHERE \n                    device = $device_id \n                    AND type = 'gps'\n                    AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}\n                ORDER BY `value` ASC\n                LIMIT 1\n            )\n        )\n        -- either value increased or decreased during this interval FOR LOWEST AND GREATES VALUES ONLY\n        -- not first and last ones\n        THEN 1\n        ELSE -1\n    END * ABS(MAX(`value`) - MIN(`value`)) AS result\nFROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts BETWEEN ${__from:date:seconds} AND ${__from:to:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}",
     "rawQueryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'temperature' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "queryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'pressure' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "queryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'humidity' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "GPS Altitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "queryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "rawQueryText": "SELECT ts, `value` FROM sensor_data\nWHERE device = $device_id AND type = 'gps' AND ts >= ${__to:date:seconds} - ${__from:date:seconds}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "GEO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "queryText": "SELECT lat, lot\nFROM sensor_data WHERE device = $device_id\nORDER BY ts DESC LIMIT 1",
     "rawQueryText": "SELECT lat, lot\nFROM sensor_data WHERE device = $device_id\nORDER BY ts DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}